# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/j/ws/age

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/j/ws/age

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/ws/age/CMakeFiles /home/j/ws/age//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/j/ws/age/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdl_test

# Build rule for target.
sdl_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_test
.PHONY : sdl_test

# fast build rule for target.
sdl_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/build
.PHONY : sdl_test/fast

commands/commands.o: commands/commands.cpp.o
.PHONY : commands/commands.o

# target to build an object file
commands/commands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/commands/commands.cpp.o
.PHONY : commands/commands.cpp.o

commands/commands.i: commands/commands.cpp.i
.PHONY : commands/commands.i

# target to preprocess a source file
commands/commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/commands/commands.cpp.i
.PHONY : commands/commands.cpp.i

commands/commands.s: commands/commands.cpp.s
.PHONY : commands/commands.s

# target to generate assembly for a file
commands/commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/commands/commands.cpp.s
.PHONY : commands/commands.cpp.s

game/ai/action.o: game/ai/action.cpp.o
.PHONY : game/ai/action.o

# target to build an object file
game/ai/action.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/ai/action.cpp.o
.PHONY : game/ai/action.cpp.o

game/ai/action.i: game/ai/action.cpp.i
.PHONY : game/ai/action.i

# target to preprocess a source file
game/ai/action.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/ai/action.cpp.i
.PHONY : game/ai/action.cpp.i

game/ai/action.s: game/ai/action.cpp.s
.PHONY : game/ai/action.s

# target to generate assembly for a file
game/ai/action.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/ai/action.cpp.s
.PHONY : game/ai/action.cpp.s

game/entity.o: game/entity.cpp.o
.PHONY : game/entity.o

# target to build an object file
game/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/entity.cpp.o
.PHONY : game/entity.cpp.o

game/entity.i: game/entity.cpp.i
.PHONY : game/entity.i

# target to preprocess a source file
game/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/entity.cpp.i
.PHONY : game/entity.cpp.i

game/entity.s: game/entity.cpp.s
.PHONY : game/entity.s

# target to generate assembly for a file
game/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/entity.cpp.s
.PHONY : game/entity.cpp.s

game/ground.o: game/ground.cpp.o
.PHONY : game/ground.o

# target to build an object file
game/ground.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/ground.cpp.o
.PHONY : game/ground.cpp.o

game/ground.i: game/ground.cpp.i
.PHONY : game/ground.i

# target to preprocess a source file
game/ground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/ground.cpp.i
.PHONY : game/ground.cpp.i

game/ground.s: game/ground.cpp.s
.PHONY : game/ground.s

# target to generate assembly for a file
game/ground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/ground.cpp.s
.PHONY : game/ground.cpp.s

game/gst.o: game/gst.cpp.o
.PHONY : game/gst.o

# target to build an object file
game/gst.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/gst.cpp.o
.PHONY : game/gst.cpp.o

game/gst.i: game/gst.cpp.i
.PHONY : game/gst.i

# target to preprocess a source file
game/gst.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/gst.cpp.i
.PHONY : game/gst.cpp.i

game/gst.s: game/gst.cpp.s
.PHONY : game/gst.s

# target to generate assembly for a file
game/gst.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/gst.cpp.s
.PHONY : game/gst.cpp.s

game/load.o: game/load.cpp.o
.PHONY : game/load.o

# target to build an object file
game/load.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/load.cpp.o
.PHONY : game/load.cpp.o

game/load.i: game/load.cpp.i
.PHONY : game/load.i

# target to preprocess a source file
game/load.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/load.cpp.i
.PHONY : game/load.cpp.i

game/load.s: game/load.cpp.s
.PHONY : game/load.s

# target to generate assembly for a file
game/load.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/load.cpp.s
.PHONY : game/load.cpp.s

game/menu.o: game/menu.cpp.o
.PHONY : game/menu.o

# target to build an object file
game/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/menu.cpp.o
.PHONY : game/menu.cpp.o

game/menu.i: game/menu.cpp.i
.PHONY : game/menu.i

# target to preprocess a source file
game/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/menu.cpp.i
.PHONY : game/menu.cpp.i

game/menu.s: game/menu.cpp.s
.PHONY : game/menu.s

# target to generate assembly for a file
game/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/menu.cpp.s
.PHONY : game/menu.cpp.s

game/playercontrol.o: game/playercontrol.cpp.o
.PHONY : game/playercontrol.o

# target to build an object file
game/playercontrol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/playercontrol.cpp.o
.PHONY : game/playercontrol.cpp.o

game/playercontrol.i: game/playercontrol.cpp.i
.PHONY : game/playercontrol.i

# target to preprocess a source file
game/playercontrol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/playercontrol.cpp.i
.PHONY : game/playercontrol.cpp.i

game/playercontrol.s: game/playercontrol.cpp.s
.PHONY : game/playercontrol.s

# target to generate assembly for a file
game/playercontrol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/playercontrol.cpp.s
.PHONY : game/playercontrol.cpp.s

game/tech.o: game/tech.cpp.o
.PHONY : game/tech.o

# target to build an object file
game/tech.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/tech.cpp.o
.PHONY : game/tech.cpp.o

game/tech.i: game/tech.cpp.i
.PHONY : game/tech.i

# target to preprocess a source file
game/tech.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/tech.cpp.i
.PHONY : game/tech.cpp.i

game/tech.s: game/tech.cpp.s
.PHONY : game/tech.s

# target to generate assembly for a file
game/tech.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/tech.cpp.s
.PHONY : game/tech.cpp.s

game/tile.o: game/tile.cpp.o
.PHONY : game/tile.o

# target to build an object file
game/tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/tile.cpp.o
.PHONY : game/tile.cpp.o

game/tile.i: game/tile.cpp.i
.PHONY : game/tile.i

# target to preprocess a source file
game/tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/tile.cpp.i
.PHONY : game/tile.cpp.i

game/tile.s: game/tile.cpp.s
.PHONY : game/tile.s

# target to generate assembly for a file
game/tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/tile.cpp.s
.PHONY : game/tile.cpp.s

game/view.o: game/view.cpp.o
.PHONY : game/view.o

# target to build an object file
game/view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/view.cpp.o
.PHONY : game/view.cpp.o

game/view.i: game/view.cpp.i
.PHONY : game/view.i

# target to preprocess a source file
game/view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/view.cpp.i
.PHONY : game/view.cpp.i

game/view.s: game/view.cpp.s
.PHONY : game/view.s

# target to generate assembly for a file
game/view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/game/view.cpp.s
.PHONY : game/view.cpp.s

graphics/graphics.o: graphics/graphics.cpp.o
.PHONY : graphics/graphics.o

# target to build an object file
graphics/graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/graphics/graphics.cpp.o
.PHONY : graphics/graphics.cpp.o

graphics/graphics.i: graphics/graphics.cpp.i
.PHONY : graphics/graphics.i

# target to preprocess a source file
graphics/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/graphics/graphics.cpp.i
.PHONY : graphics/graphics.cpp.i

graphics/graphics.s: graphics/graphics.cpp.s
.PHONY : graphics/graphics.s

# target to generate assembly for a file
graphics/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/graphics/graphics.cpp.s
.PHONY : graphics/graphics.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/main.cpp.s
.PHONY : main.cpp.s

timing/timing.o: timing/timing.cpp.o
.PHONY : timing/timing.o

# target to build an object file
timing/timing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/timing/timing.cpp.o
.PHONY : timing/timing.cpp.o

timing/timing.i: timing/timing.cpp.i
.PHONY : timing/timing.i

# target to preprocess a source file
timing/timing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/timing/timing.cpp.i
.PHONY : timing/timing.cpp.i

timing/timing.s: timing/timing.cpp.s
.PHONY : timing/timing.s

# target to generate assembly for a file
timing/timing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_test.dir/build.make CMakeFiles/sdl_test.dir/timing/timing.cpp.s
.PHONY : timing/timing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl_test"
	@echo "... commands/commands.o"
	@echo "... commands/commands.i"
	@echo "... commands/commands.s"
	@echo "... game/ai/action.o"
	@echo "... game/ai/action.i"
	@echo "... game/ai/action.s"
	@echo "... game/entity.o"
	@echo "... game/entity.i"
	@echo "... game/entity.s"
	@echo "... game/ground.o"
	@echo "... game/ground.i"
	@echo "... game/ground.s"
	@echo "... game/gst.o"
	@echo "... game/gst.i"
	@echo "... game/gst.s"
	@echo "... game/load.o"
	@echo "... game/load.i"
	@echo "... game/load.s"
	@echo "... game/menu.o"
	@echo "... game/menu.i"
	@echo "... game/menu.s"
	@echo "... game/playercontrol.o"
	@echo "... game/playercontrol.i"
	@echo "... game/playercontrol.s"
	@echo "... game/tech.o"
	@echo "... game/tech.i"
	@echo "... game/tech.s"
	@echo "... game/tile.o"
	@echo "... game/tile.i"
	@echo "... game/tile.s"
	@echo "... game/view.o"
	@echo "... game/view.i"
	@echo "... game/view.s"
	@echo "... graphics/graphics.o"
	@echo "... graphics/graphics.i"
	@echo "... graphics/graphics.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... timing/timing.o"
	@echo "... timing/timing.i"
	@echo "... timing/timing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

