# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\jaksk\Desktop\dev\_cpp\age

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\jaksk\Desktop\dev\_cpp\age

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\jaksk\Desktop\dev\_cpp\age\CMakeFiles C:\Users\jaksk\Desktop\dev\_cpp\age\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\jaksk\Desktop\dev\_cpp\age\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdl_test

# Build rule for target.
sdl_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sdl_test
.PHONY : sdl_test

# fast build rule for target.
sdl_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/build
.PHONY : sdl_test/fast

commands/commands.obj: commands/commands.cpp.obj

.PHONY : commands/commands.obj

# target to build an object file
commands/commands.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/commands/commands.cpp.obj
.PHONY : commands/commands.cpp.obj

commands/commands.i: commands/commands.cpp.i

.PHONY : commands/commands.i

# target to preprocess a source file
commands/commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/commands/commands.cpp.i
.PHONY : commands/commands.cpp.i

commands/commands.s: commands/commands.cpp.s

.PHONY : commands/commands.s

# target to generate assembly for a file
commands/commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/commands/commands.cpp.s
.PHONY : commands/commands.cpp.s

game/entity.obj: game/entity.cpp.obj

.PHONY : game/entity.obj

# target to build an object file
game/entity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/entity.cpp.obj
.PHONY : game/entity.cpp.obj

game/entity.i: game/entity.cpp.i

.PHONY : game/entity.i

# target to preprocess a source file
game/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/entity.cpp.i
.PHONY : game/entity.cpp.i

game/entity.s: game/entity.cpp.s

.PHONY : game/entity.s

# target to generate assembly for a file
game/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/entity.cpp.s
.PHONY : game/entity.cpp.s

game/ground.obj: game/ground.cpp.obj

.PHONY : game/ground.obj

# target to build an object file
game/ground.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/ground.cpp.obj
.PHONY : game/ground.cpp.obj

game/ground.i: game/ground.cpp.i

.PHONY : game/ground.i

# target to preprocess a source file
game/ground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/ground.cpp.i
.PHONY : game/ground.cpp.i

game/ground.s: game/ground.cpp.s

.PHONY : game/ground.s

# target to generate assembly for a file
game/ground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/ground.cpp.s
.PHONY : game/ground.cpp.s

game/gst.obj: game/gst.cpp.obj

.PHONY : game/gst.obj

# target to build an object file
game/gst.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/gst.cpp.obj
.PHONY : game/gst.cpp.obj

game/gst.i: game/gst.cpp.i

.PHONY : game/gst.i

# target to preprocess a source file
game/gst.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/gst.cpp.i
.PHONY : game/gst.cpp.i

game/gst.s: game/gst.cpp.s

.PHONY : game/gst.s

# target to generate assembly for a file
game/gst.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/gst.cpp.s
.PHONY : game/gst.cpp.s

game/menu.obj: game/menu.cpp.obj

.PHONY : game/menu.obj

# target to build an object file
game/menu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/menu.cpp.obj
.PHONY : game/menu.cpp.obj

game/menu.i: game/menu.cpp.i

.PHONY : game/menu.i

# target to preprocess a source file
game/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/menu.cpp.i
.PHONY : game/menu.cpp.i

game/menu.s: game/menu.cpp.s

.PHONY : game/menu.s

# target to generate assembly for a file
game/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/menu.cpp.s
.PHONY : game/menu.cpp.s

game/playercontrol.obj: game/playercontrol.cpp.obj

.PHONY : game/playercontrol.obj

# target to build an object file
game/playercontrol.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/playercontrol.cpp.obj
.PHONY : game/playercontrol.cpp.obj

game/playercontrol.i: game/playercontrol.cpp.i

.PHONY : game/playercontrol.i

# target to preprocess a source file
game/playercontrol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/playercontrol.cpp.i
.PHONY : game/playercontrol.cpp.i

game/playercontrol.s: game/playercontrol.cpp.s

.PHONY : game/playercontrol.s

# target to generate assembly for a file
game/playercontrol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/playercontrol.cpp.s
.PHONY : game/playercontrol.cpp.s

game/tile.obj: game/tile.cpp.obj

.PHONY : game/tile.obj

# target to build an object file
game/tile.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/tile.cpp.obj
.PHONY : game/tile.cpp.obj

game/tile.i: game/tile.cpp.i

.PHONY : game/tile.i

# target to preprocess a source file
game/tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/tile.cpp.i
.PHONY : game/tile.cpp.i

game/tile.s: game/tile.cpp.s

.PHONY : game/tile.s

# target to generate assembly for a file
game/tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/tile.cpp.s
.PHONY : game/tile.cpp.s

game/view.obj: game/view.cpp.obj

.PHONY : game/view.obj

# target to build an object file
game/view.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/view.cpp.obj
.PHONY : game/view.cpp.obj

game/view.i: game/view.cpp.i

.PHONY : game/view.i

# target to preprocess a source file
game/view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/view.cpp.i
.PHONY : game/view.cpp.i

game/view.s: game/view.cpp.s

.PHONY : game/view.s

# target to generate assembly for a file
game/view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/game/view.cpp.s
.PHONY : game/view.cpp.s

graphics/graphics.obj: graphics/graphics.cpp.obj

.PHONY : graphics/graphics.obj

# target to build an object file
graphics/graphics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/graphics/graphics.cpp.obj
.PHONY : graphics/graphics.cpp.obj

graphics/graphics.i: graphics/graphics.cpp.i

.PHONY : graphics/graphics.i

# target to preprocess a source file
graphics/graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/graphics/graphics.cpp.i
.PHONY : graphics/graphics.cpp.i

graphics/graphics.s: graphics/graphics.cpp.s

.PHONY : graphics/graphics.s

# target to generate assembly for a file
graphics/graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/graphics/graphics.cpp.s
.PHONY : graphics/graphics.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/main.cpp.s
.PHONY : main.cpp.s

timing/timing.obj: timing/timing.cpp.obj

.PHONY : timing/timing.obj

# target to build an object file
timing/timing.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/timing/timing.cpp.obj
.PHONY : timing/timing.cpp.obj

timing/timing.i: timing/timing.cpp.i

.PHONY : timing/timing.i

# target to preprocess a source file
timing/timing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/timing/timing.cpp.i
.PHONY : timing/timing.cpp.i

timing/timing.s: timing/timing.cpp.s

.PHONY : timing/timing.s

# target to generate assembly for a file
timing/timing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sdl_test.dir\build.make CMakeFiles/sdl_test.dir/timing/timing.cpp.s
.PHONY : timing/timing.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... sdl_test
	@echo ... commands/commands.obj
	@echo ... commands/commands.i
	@echo ... commands/commands.s
	@echo ... game/entity.obj
	@echo ... game/entity.i
	@echo ... game/entity.s
	@echo ... game/ground.obj
	@echo ... game/ground.i
	@echo ... game/ground.s
	@echo ... game/gst.obj
	@echo ... game/gst.i
	@echo ... game/gst.s
	@echo ... game/menu.obj
	@echo ... game/menu.i
	@echo ... game/menu.s
	@echo ... game/playercontrol.obj
	@echo ... game/playercontrol.i
	@echo ... game/playercontrol.s
	@echo ... game/tile.obj
	@echo ... game/tile.i
	@echo ... game/tile.s
	@echo ... game/view.obj
	@echo ... game/view.i
	@echo ... game/view.s
	@echo ... graphics/graphics.obj
	@echo ... graphics/graphics.i
	@echo ... graphics/graphics.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... timing/timing.obj
	@echo ... timing/timing.i
	@echo ... timing/timing.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

